### ISSUE TITLE
[tracker] Automation tasks to tackle

### ISSUE THREAD

**Issue by rmohr** [kubevirt/project-infra#344]
A non-exhaustive list of automation flows which we need to add.

### kubevirt code updates

- [ ] automatic periodic vendor update on master
- [ ] automatic k8s-dependency updates on new k8s releases
- [ ] automatic update of kubevirtci in kubevirt/kubevirt if a new PR is merged in kubevirtci
- [ ] finish the dependency mirror prow plugin, so that maintainers can write `/upload` (or alternatively run a postsubmit job which does the update and creates a PR).

### release engineering

 - [x] release-note collecting from the PRs
  * add them to the pre-release on the github release page
  * do a release-note PR once the release is published with the cleaned release notes
 - [x] job-forking: Fork the CI jobs when we create a new release branch
- [ ] pushing  latest release version to gcs to a well known location, so that the docs can reference the latest release without docs update.

### ci clusters

- [ ] building kubevirtci clusters in postsubmitjobs when changes are pushed, and pushing the new shasums to gcs
- [ ] automatically copying the provision scripts for new k8s clusters and adding build jobs for it when a new k8s release happens (also requires untangling the merged provision script, so that we can simply copy/paste)
- [ ] running k8s conformance tests on kubevirtci clusters
- [ ] automatically propose enabling ci lanes once they are green for a definded sequence of runs

### prow improvements

- [x] switch to crier for github status reporting
- [ ] enable in deck the feature to re-trigger jobs from the UI
- [ ] job dashboards and alertrules with the new prometheus metrics to identify errors quicker

There exists already a set of tools which can help us achieving this:

*  https://github.com/kubernetes/test-infra/tree/master/robots/pr-creator
* https://github.com/kubernetes/test-infra/tree/master/robots/issue-creator
* https://github.com/kubernetes/release/tree/master/cmd/release-notes

**Comment by rmohr** [comment]
@gbenhaim @danielBelenky @dhiller @qinqon FYI

**Comment by qinqon** [comment]
@rmohr about jobs forking I know you don't like distributing job confif at projects but that would help there I suppose, maybe we can distribute the configuration and have a whitelist of projects that have ci config there so they need the ok-to-test.

**Comment by qinqon** [comment]
About releas-notes have a PR for kubernetes-nmstate although it does not use a postsubmit yet 
https://github.com/nmstate/kubernetes-nmstate/pull/455

**Comment by danielBelenky** [comment]
Some of the topics here are handled by the now merged release tool.
